In [ ]:

import numpy as np 


In [ ]:

Plist = [1,2,3,4,5]

num_array = np.array([1,2,3,4,4])

print("operation on python list : " , [x + 10 for x in Plist])


print("num arry", num_array + 10)
print("python list", (Plist))


operation on python list :  [11, 12, 13, 14, 15]
num arry [11 12 13 14 14]
python list [1, 2, 3, 4, 5]


In [ ]:
import time
import numpy as np

size = 1000000

python_list = list(range(size))

num = np.arange(size)

print("--- Performance Test ---")
print(f"Array size: {size:,} elements")

# Python list
start = time.time()

result_python = [x + 10 for x in python_list]

python_time = time.time() - start

print(f"Python list: {python_time:.4f} seconds")


# NumPy
start = time.time()

result_numpy = num + 10

numpy_time = time.time() - start

print(f"NumPy array: {numpy_time:.4f} seconds")


# Speed comparison
speedup = python_time / numpy_time

print(f"\nNumPy is {speedup:.2f}x faster than Python list")

--- Performance Test ---
Array size: 10,000 elements
Python list: 0.0003 seconds
NumPy array: 0.0004 seconds

NumPy is 0.73x faster than Python list


In [ ]:

# 1. From a Python list
arr1 = np.array([1, 2, 3, 4, 5])

# 2. Using arange()
arr2 = np.arange(5)

# 3. Using zeros()
arr3 = np.zeros(5)

# 4. Using ones()
arr4 = np.ones(5)

# 5. Using random numbers
arr5 = np.random.rand(5)


print(arr1)
print(arr2)
print(arr3)
print(arr4)
print(arr5)

[1 2 3 4 5]
[0 1 2 3 4]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[0.39452119 0.15321796 0.93235173 0.17923076 0.57859072]


In [3]:
import numpy as np

# =========================
# 1. 2D NumPy Array
# =========================

arr2d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("2D Array:")
print(arr2d)

print("Shape:", arr2d.shape)
print("Dimensions:", arr2d.ndim)
print("Size:", arr2d.size)
print("Data type:", arr2d.dtype)


# =========================
# 2. 3D NumPy Array
# =========================

arr3d = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

print("\n3D Array:")
print(arr3d)

print("Shape:", arr3d.shape)
print("Dimensions:", arr3d.ndim)
print("Size:", arr3d.size)
print("Data type:", arr3d.dtype)


# =========================
# 3. 2D Array with specific number
# =========================

arr2d_specific = np.full((3, 4), 7)

print("\n2D Array filled with 7:")
print(arr2d_specific)


# =========================
# 4. 3D Array with specific number
# =========================

arr3d_specific = np.full((2, 3, 4), 5)

print("\n3D Array filled with 5:")
print(arr3d_specific)

2D Array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimensions: 2
Size: 6
Data type: int64

3D Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape: (2, 2, 3)
Dimensions: 3
Size: 12
Data type: int64

2D Array filled with 7:
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]

3D Array filled with 5:
[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]

 [[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]]


In [ ]:
import numpy as np
zeero = np.zeros(4)

print(zeero)

In [ ]:
op = np.array([1,2,3,4,5])

print(op.sum())
print(op.mean())
print(op.max())
print(op.min())
print(op.std())


In [ ]:
axis = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

axis.sum(axis=0) #column adding

axis.sum(axis= 1) # row addition

In [ ]:
filter = np.array([10, 20, 30, 40, 50])
# we can do boolena filtering to produce new array



#we can generate random numbers 

In [ ]:
# we can reference one arary to another..
# b = a we can not creating another aray
# for copying we use a function
